//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.12 at 07:28:45 PM MSK 
//


package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ArticleCollectionTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ArticleCollectionEditor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "articleCollectionTitle",
    "articleCollectionEditor"
})
@XmlRootElement(name = "ArticleCollection")
public class ArticleCollection {

    @XmlElement(name = "ArticleCollectionTitle", required = true)
    protected String articleCollectionTitle;
    @XmlElement(name = "ArticleCollectionEditor", required = true)
    protected String articleCollectionEditor;
    @XmlAttribute(name = "ID")
    protected String id;

    /**
     * Gets the value of the articleCollectionTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArticleCollectionTitle() {
        return articleCollectionTitle;
    }

    /**
     * Sets the value of the articleCollectionTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArticleCollectionTitle(String value) {
        this.articleCollectionTitle = value;
    }

    /**
     * Gets the value of the articleCollectionEditor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArticleCollectionEditor() {
        return articleCollectionEditor;
    }

    /**
     * Sets the value of the articleCollectionEditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArticleCollectionEditor(String value) {
        this.articleCollectionEditor = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
