//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.12 at 07:28:45 PM MSK 
//


package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetadataGrant">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AbstractGrant">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BodyPDFGrant">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BodyHTMLGrant">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BibliographyGrant">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ESMGrant">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadataGrant",
    "abstractGrant",
    "bodyPDFGrant",
    "bodyHTMLGrant",
    "bibliographyGrant",
    "esmGrant"
})
@XmlRootElement(name = "ArticleGrants")
public class ArticleGrants {

    @XmlElement(name = "MetadataGrant", required = true)
    protected ArticleGrants.MetadataGrant metadataGrant;
    @XmlElement(name = "AbstractGrant", required = true)
    protected ArticleGrants.AbstractGrant abstractGrant;
    @XmlElement(name = "BodyPDFGrant", required = true)
    protected ArticleGrants.BodyPDFGrant bodyPDFGrant;
    @XmlElement(name = "BodyHTMLGrant", required = true)
    protected ArticleGrants.BodyHTMLGrant bodyHTMLGrant;
    @XmlElement(name = "BibliographyGrant", required = true)
    protected ArticleGrants.BibliographyGrant bibliographyGrant;
    @XmlElement(name = "ESMGrant", required = true)
    protected ArticleGrants.ESMGrant esmGrant;
    @XmlAttribute(name = "Type")
    protected String type;

    /**
     * Gets the value of the metadataGrant property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleGrants.MetadataGrant }
     *     
     */
    public ArticleGrants.MetadataGrant getMetadataGrant() {
        return metadataGrant;
    }

    /**
     * Sets the value of the metadataGrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleGrants.MetadataGrant }
     *     
     */
    public void setMetadataGrant(ArticleGrants.MetadataGrant value) {
        this.metadataGrant = value;
    }

    /**
     * Gets the value of the abstractGrant property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleGrants.AbstractGrant }
     *     
     */
    public ArticleGrants.AbstractGrant getAbstractGrant() {
        return abstractGrant;
    }

    /**
     * Sets the value of the abstractGrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleGrants.AbstractGrant }
     *     
     */
    public void setAbstractGrant(ArticleGrants.AbstractGrant value) {
        this.abstractGrant = value;
    }

    /**
     * Gets the value of the bodyPDFGrant property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleGrants.BodyPDFGrant }
     *     
     */
    public ArticleGrants.BodyPDFGrant getBodyPDFGrant() {
        return bodyPDFGrant;
    }

    /**
     * Sets the value of the bodyPDFGrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleGrants.BodyPDFGrant }
     *     
     */
    public void setBodyPDFGrant(ArticleGrants.BodyPDFGrant value) {
        this.bodyPDFGrant = value;
    }

    /**
     * Gets the value of the bodyHTMLGrant property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleGrants.BodyHTMLGrant }
     *     
     */
    public ArticleGrants.BodyHTMLGrant getBodyHTMLGrant() {
        return bodyHTMLGrant;
    }

    /**
     * Sets the value of the bodyHTMLGrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleGrants.BodyHTMLGrant }
     *     
     */
    public void setBodyHTMLGrant(ArticleGrants.BodyHTMLGrant value) {
        this.bodyHTMLGrant = value;
    }

    /**
     * Gets the value of the bibliographyGrant property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleGrants.BibliographyGrant }
     *     
     */
    public ArticleGrants.BibliographyGrant getBibliographyGrant() {
        return bibliographyGrant;
    }

    /**
     * Sets the value of the bibliographyGrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleGrants.BibliographyGrant }
     *     
     */
    public void setBibliographyGrant(ArticleGrants.BibliographyGrant value) {
        this.bibliographyGrant = value;
    }

    /**
     * Gets the value of the esmGrant property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleGrants.ESMGrant }
     *     
     */
    public ArticleGrants.ESMGrant getESMGrant() {
        return esmGrant;
    }

    /**
     * Sets the value of the esmGrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleGrants.ESMGrant }
     *     
     */
    public void setESMGrant(ArticleGrants.ESMGrant value) {
        this.esmGrant = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AbstractGrant {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Grant")
        protected String grant;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the grant property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrant() {
            return grant;
        }

        /**
         * Sets the value of the grant property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrant(String value) {
            this.grant = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class BibliographyGrant {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Grant")
        protected String grant;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the grant property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrant() {
            return grant;
        }

        /**
         * Sets the value of the grant property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrant(String value) {
            this.grant = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class BodyHTMLGrant {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Grant")
        protected String grant;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the grant property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrant() {
            return grant;
        }

        /**
         * Sets the value of the grant property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrant(String value) {
            this.grant = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class BodyPDFGrant {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Grant")
        protected String grant;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the grant property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrant() {
            return grant;
        }

        /**
         * Sets the value of the grant property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrant(String value) {
            this.grant = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ESMGrant {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Grant")
        protected String grant;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the grant property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrant() {
            return grant;
        }

        /**
         * Sets the value of the grant property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrant(String value) {
            this.grant = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Grant" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MetadataGrant {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Grant")
        protected String grant;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the grant property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrant() {
            return grant;
        }

        /**
         * Sets the value of the grant property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrant(String value) {
            this.grant = value;
        }

    }

}
