//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.12 at 07:28:45 PM MSK 
//

package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ArticleID"/>
 *         &lt;element ref="{}ArticleExternalID" minOccurs="0"/>
 *         &lt;element ref="{}ArticleDOI"/>
 *         &lt;element ref="{}ArticleCitationID" minOccurs="0"/>
 *         &lt;element ref="{}ArticleSequenceNumber"/>
 *         &lt;element ref="{}ArticleRelatedObject"/>
 *         &lt;element ref="{}ArticleSuperTitle" minOccurs="0"/>
 *         &lt;element ref="{}ArticleTitle"/>
 *         &lt;element ref="{}ArticleSubTitle" minOccurs="0"/>
 *         &lt;element ref="{}ArticleClassification" minOccurs="0"/>
 *         &lt;element ref="{}ArticleCategory" minOccurs="0"/>
 *         &lt;element ref="{}ArticleSubCategory" minOccurs="0"/>
 *         &lt;element ref="{}ArticleCollection" minOccurs="0"/>
 *         &lt;element ref="{}ArticleFirstPage"/>
 *         &lt;element ref="{}ArticleLastPage"/>
 *         &lt;element ref="{}ArticleHistory"/>
 *         &lt;element ref="{}ArticleEditorialResponsibility" minOccurs="0"/>
 *         &lt;element ref="{}ArticleFundingInformation" minOccurs="0"/>
 *         &lt;element ref="{}ArticleCopyright"/>
 *         &lt;element ref="{}ArticleGrants" minOccurs="0"/>
 *         &lt;element ref="{}ArticleContext"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Language" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ArticleType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TocLevels" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NumberingStyle" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ContainsESM" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ArticleCitation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OutputMedium" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "articleID",
        "articleExternalID",
        "articleDOI",
        "articleCitationID",
        "articleSequenceNumber",
        "articleRelatedObject",
        "articleSuperTitle",
        "articleTitle",
        "articleSubTitle",
        "articleClassification",
        "articleCategory",
        "articleSubCategory",
        "articleCollection",
        "articleFirstPage",
        "articleLastPage",
        "articleHistory",
        "articleEditorialResponsibility",
        "articleFundingInformation",
        "articleCopyright",
        "articleGrants",
        "articleContext",
        "erroneousArticleFirstPage",
        "erroneousArticleLastPage"

})
@XmlRootElement(name = "ArticleInfo")
public class ArticleInfo {
    
    
    @XmlElement(name = "ArticleID", required = true)
    protected String articleID;
    
    @XmlElement(name = "ArticleExternalID")
    protected ArticleExternalID articleExternalID;
    
    @XmlElement(name = "ArticleDOI", required = true)
    protected String articleDOI;
    
    @XmlElement(name = "ArticleCitationID")
    protected String articleCitationID;
    
    @XmlElement(name = "ArticleSequenceNumber", required = true)
    protected String articleSequenceNumber;
    
    @XmlElement(name = "ArticleRelatedObject", required = true)
    protected ArticleRelatedObject articleRelatedObject;
    
    @XmlElement(name = "ArticleSuperTitle")
    protected ArticleSuperTitle articleSuperTitle;
    
    @XmlElement(name = "ArticleTitle", required = true)
    protected ArticleTitle articleTitle;
    
    @XmlElement(name = "ArticleSubTitle")
    protected ArticleSubTitle articleSubTitle;
    
    @XmlElement(name = "ArticleClassification")
    protected ArticleClassification articleClassification;
    
    @XmlElement(name = "ArticleCategory")
    protected String articleCategory;
    
    @XmlElement(name = "ArticleSubCategory")
    protected String articleSubCategory;
    
    @XmlElement(name = "ArticleCollection")
    protected ArticleCollection articleCollection;
    
    @XmlElement(name = "ArticleFirstPage", required = true)
    protected String articleFirstPage;
    
    @XmlElement(name = "ArticleLastPage", required = true)
    protected String articleLastPage;
    
    @XmlElement(name = "ArticleHistory", required = true)
    protected ArticleHistory articleHistory;
    
    @XmlElement(name = "ArticleEditorialResponsibility")
    protected String articleEditorialResponsibility;
    
    @XmlElement(name = "ArticleFundingInformation")
    protected ArticleFundingInformation articleFundingInformation;
    
    @XmlElement(name = "ArticleCopyright", required = true)
    protected ArticleCopyright articleCopyright;
    
    @XmlElement(name = "ArticleGrants")
    protected ArticleGrants articleGrants;
    
    @XmlElement(name = "ArticleContext", required = true)
    protected ArticleContext articleContext;
    
    @XmlAttribute(name = "Language", required = true)
    protected String language;
    
    @XmlAttribute(name = "ArticleType", required = true)
    protected String articleType;
    
    @XmlAttribute(name = "TocLevels", required = true)
    protected String tocLevels;
    
    @XmlAttribute(name = "NumberingStyle", required = true)
    protected String numberingStyle;
    
    @XmlAttribute(name = "ContainsESM", required = true)
    protected String containsESM;
    
    @XmlAttribute(name = "ArticleCitation")
    protected String articleCitation;
    
    @XmlAttribute(name = "OutputMedium")
    protected String outputMedium;
    
    @XmlElement(name = "ErroneousArticleFirstPage")
    protected String erroneousArticleFirstPage;
    
    @XmlElement(name = "ErroneousArticleLastPage")
    protected String erroneousArticleLastPage;
    
    /**
     * Gets the value of the articleID property.
     * 
     * @return possible object is {@link String }
     */
    public String getArticleID() {
        return articleID;
    }
    
    /**
     * Sets the value of the articleID property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArticleID(final String value) {
        this.articleID = value;
    }
    
    /**
     * Gets the value of the articleExternalID property.
     * 
     * @return possible object is {@link ArticleExternalID }
     */
    public ArticleExternalID getArticleExternalID() {
        return articleExternalID;
    }
    
    /**
     * Sets the value of the articleExternalID property.
     * 
     * @param value allowed object is {@link ArticleExternalID }
     */
    public void setArticleExternalID(final ArticleExternalID value) {
        this.articleExternalID = value;
    }
    
    /**
     * Gets the value of the articleDOI property.
     * 
     * @return possible object is {@link String }
     */
    public String getArticleDOI() {
        return articleDOI;
    }
    
    /**
     * Sets the value of the articleDOI property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArticleDOI(final String value) {
        this.articleDOI = value;
    }
    
    /**
     * Gets the value of the articleCitationID property.
     * 
     * @return possible object is {@link String }
     */
    public String getArticleCitationID() {
        return articleCitationID;
    }
    
    /**
     * Sets the value of the articleCitationID property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArticleCitationID(final String value) {
        this.articleCitationID = value;
    }
    
    /**
     * Gets the value of the articleSequenceNumber property.
     * 
     * @return possible object is {@link String }
     */
    public String getArticleSequenceNumber() {
        return articleSequenceNumber;
    }
    
    /**
     * Sets the value of the articleSequenceNumber property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArticleSequenceNumber(final String value) {
        this.articleSequenceNumber = value;
    }
    
    /**
     * Gets the value of the articleRelatedObject property.
     * 
     * @return possible object is {@link ArticleRelatedObject }
     */
    public ArticleRelatedObject getArticleRelatedObject() {
        return articleRelatedObject;
    }
    
    /**
     * Sets the value of the articleRelatedObject property.
     * 
     * @param value allowed object is {@link ArticleRelatedObject }
     */
    public void setArticleRelatedObject(final ArticleRelatedObject value) {
        this.articleRelatedObject = value;
    }
    
    /**
     * Gets the value of the articleSuperTitle property.
     * 
     * @return possible object is {@link ArticleSuperTitle }
     */
    public ArticleSuperTitle getArticleSuperTitle() {
        return articleSuperTitle;
    }
    
    /**
     * Sets the value of the articleSuperTitle property.
     * 
     * @param value allowed object is {@link ArticleSuperTitle }
     */
    public void setArticleSuperTitle(final ArticleSuperTitle value) {
        this.articleSuperTitle = value;
    }
    
    /**
     * Gets the value of the articleTitle property.
     * 
     * @return possible object is {@link ArticleTitle }
     */
    public ArticleTitle getArticleTitle() {
        return articleTitle;
    }
    
    /**
     * Sets the value of the articleTitle property.
     * 
     * @param value allowed object is {@link ArticleTitle }
     */
    public void setArticleTitle(final ArticleTitle value) {
        this.articleTitle = value;
    }
    
    /**
     * Gets the value of the articleSubTitle property.
     * 
     * @return possible object is {@link ArticleSubTitle }
     */
    public ArticleSubTitle getArticleSubTitle() {
        return articleSubTitle;
    }
    
    /**
     * Sets the value of the articleSubTitle property.
     * 
     * @param value allowed object is {@link ArticleSubTitle }
     */
    public void setArticleSubTitle(final ArticleSubTitle value) {
        this.articleSubTitle = value;
    }
    
    /**
     * Gets the value of the articleClassification property.
     * 
     * @return possible object is {@link ArticleClassification }
     */
    public ArticleClassification getArticleClassification() {
        return articleClassification;
    }
    
    /**
     * Sets the value of the articleClassification property.
     * 
     * @param value allowed object is {@link ArticleClassification }
     */
    public void setArticleClassification(final ArticleClassification value) {
        this.articleClassification = value;
    }
    
    /**
     * Gets the value of the articleCategory property.
     * 
     * @return possible object is {@link String }
     */
    public String getArticleCategory() {
        return articleCategory;
    }
    
    /**
     * Sets the value of the articleCategory property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArticleCategory(final String value) {
        this.articleCategory = value;
    }
    
    /**
     * Gets the value of the articleSubCategory property.
     * 
     * @return possible object is {@link String }
     */
    public String getArticleSubCategory() {
        return articleSubCategory;
    }
    
    /**
     * Sets the value of the articleSubCategory property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArticleSubCategory(final String value) {
        this.articleSubCategory = value;
    }
    
    /**
     * Gets the value of the articleCollection property.
     * 
     * @return possible object is {@link ArticleCollection }
     */
    public ArticleCollection getArticleCollection() {
        return articleCollection;
    }
    
    /**
     * Sets the value of the articleCollection property.
     * 
     * @param value allowed object is {@link ArticleCollection }
     */
    public void setArticleCollection(final ArticleCollection value) {
        this.articleCollection = value;
    }
    
    /**
     * Gets the value of the articleFirstPage property.
     * 
     * @return possible object is {@link String }
     */
    public String getArticleFirstPage() {
        return articleFirstPage;
    }
    
    /**
     * Sets the value of the articleFirstPage property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArticleFirstPage(final String value) {
        this.articleFirstPage = value;
    }
    
    /**
     * Gets the value of the articleLastPage property.
     * 
     * @return possible object is {@link String }
     */
    public String getArticleLastPage() {
        return articleLastPage;
    }
    
    /**
     * Sets the value of the articleLastPage property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArticleLastPage(final String value) {
        this.articleLastPage = value;
    }
    
    /**
     * Gets the value of the articleHistory property.
     * 
     * @return possible object is {@link ArticleHistory }
     */
    public ArticleHistory getArticleHistory() {
        return articleHistory;
    }
    
    /**
     * Sets the value of the articleHistory property.
     * 
     * @param value allowed object is {@link ArticleHistory }
     */
    public void setArticleHistory(final ArticleHistory value) {
        this.articleHistory = value;
    }
    
    /**
     * Gets the value of the articleEditorialResponsibility property.
     * 
     * @return possible object is {@link String }
     */
    public String getArticleEditorialResponsibility() {
        return articleEditorialResponsibility;
    }
    
    /**
     * Sets the value of the articleEditorialResponsibility property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArticleEditorialResponsibility(final String value) {
        this.articleEditorialResponsibility = value;
    }
    
    /**
     * Gets the value of the articleFundingInformation property.
     * 
     * @return possible object is {@link ArticleFundingInformation }
     */
    public ArticleFundingInformation getArticleFundingInformation() {
        return articleFundingInformation;
    }
    
    /**
     * Sets the value of the articleFundingInformation property.
     * 
     * @param value allowed object is {@link ArticleFundingInformation }
     */
    public void setArticleFundingInformation(final ArticleFundingInformation value) {
        this.articleFundingInformation = value;
    }
    
    /**
     * Gets the value of the articleCopyright property.
     * 
     * @return possible object is {@link ArticleCopyright }
     */
    public ArticleCopyright getArticleCopyright() {
        return articleCopyright;
    }
    
    /**
     * Sets the value of the articleCopyright property.
     * 
     * @param value allowed object is {@link ArticleCopyright }
     */
    public void setArticleCopyright(final ArticleCopyright value) {
        this.articleCopyright = value;
    }
    
    /**
     * Gets the value of the articleGrants property.
     * 
     * @return possible object is {@link ArticleGrants }
     */
    public ArticleGrants getArticleGrants() {
        return articleGrants;
    }
    
    /**
     * Sets the value of the articleGrants property.
     * 
     * @param value allowed object is {@link ArticleGrants }
     */
    public void setArticleGrants(final ArticleGrants value) {
        this.articleGrants = value;
    }
    
    /**
     * Gets the value of the articleContext property.
     * 
     * @return possible object is {@link ArticleContext }
     */
    public ArticleContext getArticleContext() {
        return articleContext;
    }
    
    /**
     * Sets the value of the articleContext property.
     * 
     * @param value allowed object is {@link ArticleContext }
     */
    public void setArticleContext(final ArticleContext value) {
        this.articleContext = value;
    }
    
    /**
     * Gets the value of the language property.
     * 
     * @return possible object is {@link String }
     */
    public String getLanguage() {
        return language;
    }
    
    /**
     * Sets the value of the language property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setLanguage(final String value) {
        this.language = value;
    }
    
    /**
     * Gets the value of the articleType property.
     * 
     * @return possible object is {@link String }
     */
    public String getArticleType() {
        return articleType;
    }
    
    /**
     * Sets the value of the articleType property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArticleType(final String value) {
        this.articleType = value;
    }
    
    /**
     * Gets the value of the tocLevels property.
     * 
     * @return possible object is {@link String }
     */
    public String getTocLevels() {
        return tocLevels;
    }
    
    /**
     * Sets the value of the tocLevels property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTocLevels(final String value) {
        this.tocLevels = value;
    }
    
    /**
     * Gets the value of the numberingStyle property.
     * 
     * @return possible object is {@link String }
     */
    public String getNumberingStyle() {
        return numberingStyle;
    }
    
    /**
     * Sets the value of the numberingStyle property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setNumberingStyle(final String value) {
        this.numberingStyle = value;
    }
    
    /**
     * Gets the value of the containsESM property.
     * 
     * @return possible object is {@link String }
     */
    public String getContainsESM() {
        return containsESM;
    }
    
    /**
     * Sets the value of the containsESM property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setContainsESM(final String value) {
        this.containsESM = value;
    }
    
    /**
     * Gets the value of the articleCitation property.
     * 
     * @return possible object is {@link String }
     */
    public String getArticleCitation() {
        return articleCitation;
    }
    
    /**
     * Sets the value of the articleCitation property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArticleCitation(final String value) {
        this.articleCitation = value;
    }
    
    /**
     * Gets the value of the outputMedium property.
     * 
     * @return possible object is {@link String }
     */
    public String getOutputMedium() {
        return outputMedium;
    }
    
    /**
     * Sets the value of the outputMedium property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setOutputMedium(final String value) {
        this.outputMedium = value;
    }
    
    /**
     * Gets the value of the erroneousArticleFirstPage property.
     * 
     * @return possible object is {@link String }
     */
    public String getErroneousArticleFirstPage() {
        return erroneousArticleFirstPage;
    }
    
    /**
     * Sets the value of the erroneousArticleFirstPage property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setErroneousArticleFirstPage(final String value) {
        this.erroneousArticleFirstPage = value;
    }
    
    /**
     * Gets the value of the erroneousArticleLastPage property.
     * 
     * @return possible object is {@link String }
     */
    public String getErroneousArticleLastPage() {
        return erroneousArticleLastPage;
    }
    
    /**
     * Sets the value of the erroneousArticleLastPage property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setErroneousArticleLastPage(final String value) {
        this.erroneousArticleLastPage = value;
    }
    
}
