//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.19 at 06:11:57 PM MSK 
//


package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CoverInfo"/>
 *         &lt;element ref="{}CoverFigure"/>
 *         &lt;element ref="{}BodyRef"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coverInfo",
    "coverFigure",
    "bodyRef"
})
@XmlRootElement(name = "Cover")
public class Cover {

    @XmlElement(name = "CoverInfo", required = true)
    protected CoverInfo coverInfo;
    @XmlElement(name = "CoverFigure", required = true)
    protected CoverFigure coverFigure;
    @XmlElement(name = "BodyRef", required = true)
    protected BodyRef bodyRef;

    /**
     * Gets the value of the coverInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CoverInfo }
     *     
     */
    public CoverInfo getCoverInfo() {
        return coverInfo;
    }

    /**
     * Sets the value of the coverInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverInfo }
     *     
     */
    public void setCoverInfo(CoverInfo value) {
        this.coverInfo = value;
    }

    /**
     * Gets the value of the coverFigure property.
     * 
     * @return
     *     possible object is
     *     {@link CoverFigure }
     *     
     */
    public CoverFigure getCoverFigure() {
        return coverFigure;
    }

    /**
     * Sets the value of the coverFigure property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverFigure }
     *     
     */
    public void setCoverFigure(CoverFigure value) {
        this.coverFigure = value;
    }

    /**
     * Gets the value of the bodyRef property.
     * 
     * @return
     *     possible object is
     *     {@link BodyRef }
     *     
     */
    public BodyRef getBodyRef() {
        return bodyRef;
    }

    /**
     * Sets the value of the bodyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyRef }
     *     
     */
    public void setBodyRef(BodyRef value) {
        this.bodyRef = value;
    }

}
