//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 03:42:42 PM MSK 
//


package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CoverPrintPDF" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CoverFigure" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FrontmatterPrintPDF" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BackmatterPrintPDF" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AdvertisementPrintPDF" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DiscreteContentObjectOnlinePDF" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DiscreteContentObjectPrintPDF" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Pit-Stop-Reports" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DiscreteContentObjectXMLWithBody" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DiscreteContentObjectXMLWithBodyRefsOnly" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DiscreteContentObjectOnlineMediaObjects" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IssuePrintPDF" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CorrectionSheet" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DeliverablesForCompoundObjects")
public class DeliverablesForCompoundObjects {

    @XmlAttribute(name = "CoverPrintPDF", required = true)
    protected String coverPrintPDF;
    @XmlAttribute(name = "CoverFigure", required = true)
    protected String coverFigure;
    @XmlAttribute(name = "FrontmatterPrintPDF", required = true)
    protected String frontmatterPrintPDF;
    @XmlAttribute(name = "BackmatterPrintPDF", required = true)
    protected String backmatterPrintPDF;
    @XmlAttribute(name = "AdvertisementPrintPDF", required = true)
    protected String advertisementPrintPDF;
    @XmlAttribute(name = "DiscreteContentObjectOnlinePDF", required = true)
    protected String discreteContentObjectOnlinePDF;
    @XmlAttribute(name = "DiscreteContentObjectPrintPDF", required = true)
    protected String discreteContentObjectPrintPDF;
    @XmlAttribute(name = "Pit-Stop-Reports", required = true)
    protected String pitStopReports;
    @XmlAttribute(name = "DiscreteContentObjectXMLWithBody", required = true)
    protected String discreteContentObjectXMLWithBody;
    @XmlAttribute(name = "DiscreteContentObjectXMLWithBodyRefsOnly", required = true)
    protected String discreteContentObjectXMLWithBodyRefsOnly;
    @XmlAttribute(name = "DiscreteContentObjectOnlineMediaObjects", required = true)
    protected String discreteContentObjectOnlineMediaObjects;
    @XmlAttribute(name = "IssuePrintPDF")
    protected String issuePrintPDF;
    @XmlAttribute(name = "CorrectionSheet")
    protected String correctionSheet;

    /**
     * Gets the value of the coverPrintPDF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverPrintPDF() {
        return coverPrintPDF;
    }

    /**
     * Sets the value of the coverPrintPDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverPrintPDF(String value) {
        this.coverPrintPDF = value;
    }

    /**
     * Gets the value of the coverFigure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverFigure() {
        return coverFigure;
    }

    /**
     * Sets the value of the coverFigure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverFigure(String value) {
        this.coverFigure = value;
    }

    /**
     * Gets the value of the frontmatterPrintPDF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontmatterPrintPDF() {
        return frontmatterPrintPDF;
    }

    /**
     * Sets the value of the frontmatterPrintPDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontmatterPrintPDF(String value) {
        this.frontmatterPrintPDF = value;
    }

    /**
     * Gets the value of the backmatterPrintPDF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackmatterPrintPDF() {
        return backmatterPrintPDF;
    }

    /**
     * Sets the value of the backmatterPrintPDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackmatterPrintPDF(String value) {
        this.backmatterPrintPDF = value;
    }

    /**
     * Gets the value of the advertisementPrintPDF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvertisementPrintPDF() {
        return advertisementPrintPDF;
    }

    /**
     * Sets the value of the advertisementPrintPDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvertisementPrintPDF(String value) {
        this.advertisementPrintPDF = value;
    }

    /**
     * Gets the value of the discreteContentObjectOnlinePDF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscreteContentObjectOnlinePDF() {
        return discreteContentObjectOnlinePDF;
    }

    /**
     * Sets the value of the discreteContentObjectOnlinePDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscreteContentObjectOnlinePDF(String value) {
        this.discreteContentObjectOnlinePDF = value;
    }

    /**
     * Gets the value of the discreteContentObjectPrintPDF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscreteContentObjectPrintPDF() {
        return discreteContentObjectPrintPDF;
    }

    /**
     * Sets the value of the discreteContentObjectPrintPDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscreteContentObjectPrintPDF(String value) {
        this.discreteContentObjectPrintPDF = value;
    }

    /**
     * Gets the value of the pitStopReports property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPitStopReports() {
        return pitStopReports;
    }

    /**
     * Sets the value of the pitStopReports property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPitStopReports(String value) {
        this.pitStopReports = value;
    }

    /**
     * Gets the value of the discreteContentObjectXMLWithBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscreteContentObjectXMLWithBody() {
        return discreteContentObjectXMLWithBody;
    }

    /**
     * Sets the value of the discreteContentObjectXMLWithBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscreteContentObjectXMLWithBody(String value) {
        this.discreteContentObjectXMLWithBody = value;
    }

    /**
     * Gets the value of the discreteContentObjectXMLWithBodyRefsOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscreteContentObjectXMLWithBodyRefsOnly() {
        return discreteContentObjectXMLWithBodyRefsOnly;
    }

    /**
     * Sets the value of the discreteContentObjectXMLWithBodyRefsOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscreteContentObjectXMLWithBodyRefsOnly(String value) {
        this.discreteContentObjectXMLWithBodyRefsOnly = value;
    }

    /**
     * Gets the value of the discreteContentObjectOnlineMediaObjects property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscreteContentObjectOnlineMediaObjects() {
        return discreteContentObjectOnlineMediaObjects;
    }

    /**
     * Sets the value of the discreteContentObjectOnlineMediaObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscreteContentObjectOnlineMediaObjects(String value) {
        this.discreteContentObjectOnlineMediaObjects = value;
    }

    /**
     * Gets the value of the issuePrintPDF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuePrintPDF() {
        return issuePrintPDF;
    }

    /**
     * Sets the value of the issuePrintPDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuePrintPDF(String value) {
        this.issuePrintPDF = value;
    }

    /**
     * Gets the value of the correctionSheet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrectionSheet() {
        return correctionSheet;
    }

    /**
     * Sets the value of the correctionSheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrectionSheet(String value) {
        this.correctionSheet = value;
    }

}
