//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.12 at 07:28:45 PM MSK 
//


package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{}DeliverablesForCompoundObjects"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}DeliverablesForDiscreteObjects"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deliverablesForCompoundObjects",
    "deliverablesForDiscreteObjects"
})
@XmlRootElement(name = "Deliverables")
public class Deliverables {

    @XmlElement(name = "DeliverablesForCompoundObjects")
    protected DeliverablesForCompoundObjects deliverablesForCompoundObjects;
    @XmlElement(name = "DeliverablesForDiscreteObjects")
    protected DeliverablesForDiscreteObjects deliverablesForDiscreteObjects;

    /**
     * Gets the value of the deliverablesForCompoundObjects property.
     * 
     * @return
     *     possible object is
     *     {@link DeliverablesForCompoundObjects }
     *     
     */
    public DeliverablesForCompoundObjects getDeliverablesForCompoundObjects() {
        return deliverablesForCompoundObjects;
    }

    /**
     * Sets the value of the deliverablesForCompoundObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliverablesForCompoundObjects }
     *     
     */
    public void setDeliverablesForCompoundObjects(DeliverablesForCompoundObjects value) {
        this.deliverablesForCompoundObjects = value;
    }

    /**
     * Gets the value of the deliverablesForDiscreteObjects property.
     * 
     * @return
     *     possible object is
     *     {@link DeliverablesForDiscreteObjects }
     *     
     */
    public DeliverablesForDiscreteObjects getDeliverablesForDiscreteObjects() {
        return deliverablesForDiscreteObjects;
    }

    /**
     * Sets the value of the deliverablesForDiscreteObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliverablesForDiscreteObjects }
     *     
     */
    public void setDeliverablesForDiscreteObjects(DeliverablesForDiscreteObjects value) {
        this.deliverablesForDiscreteObjects = value;
    }

}
