//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.19 at 06:11:57 PM MSK 
//


package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{}CoverInfo"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}IssueFrontmatterInfo"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}ArticleInfo"/>
 *           &lt;element ref="{}AuthorGroup"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}IssueBackmatterInfo"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coverInfo",
    "issueFrontmatterInfo",
    "articleInfo",
    "authorGroup",
    "issueBackmatterInfo"
})
@XmlRootElement(name = "DiscreteIssueObjectInfo")
public class DiscreteIssueObjectInfo {

    @XmlElement(name = "CoverInfo")
    protected CoverInfo coverInfo;
    @XmlElement(name = "IssueFrontmatterInfo")
    protected IssueFrontmatterInfo issueFrontmatterInfo;
    @XmlElement(name = "ArticleInfo")
    protected ArticleInfo articleInfo;
    @XmlElement(name = "AuthorGroup")
    protected AuthorGroup authorGroup;
    @XmlElement(name = "IssueBackmatterInfo")
    protected IssueBackmatterInfo issueBackmatterInfo;
    @XmlAttribute(name = "ID", required = true)
    protected String id;

    /**
     * Gets the value of the coverInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CoverInfo }
     *     
     */
    public CoverInfo getCoverInfo() {
        return coverInfo;
    }

    /**
     * Sets the value of the coverInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverInfo }
     *     
     */
    public void setCoverInfo(CoverInfo value) {
        this.coverInfo = value;
    }

    /**
     * Gets the value of the issueFrontmatterInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IssueFrontmatterInfo }
     *     
     */
    public IssueFrontmatterInfo getIssueFrontmatterInfo() {
        return issueFrontmatterInfo;
    }

    /**
     * Sets the value of the issueFrontmatterInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssueFrontmatterInfo }
     *     
     */
    public void setIssueFrontmatterInfo(IssueFrontmatterInfo value) {
        this.issueFrontmatterInfo = value;
    }

    /**
     * Gets the value of the articleInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleInfo }
     *     
     */
    public ArticleInfo getArticleInfo() {
        return articleInfo;
    }

    /**
     * Sets the value of the articleInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleInfo }
     *     
     */
    public void setArticleInfo(ArticleInfo value) {
        this.articleInfo = value;
    }

    /**
     * Gets the value of the authorGroup property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorGroup }
     *     
     */
    public AuthorGroup getAuthorGroup() {
        return authorGroup;
    }

    /**
     * Sets the value of the authorGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorGroup }
     *     
     */
    public void setAuthorGroup(AuthorGroup value) {
        this.authorGroup = value;
    }

    /**
     * Gets the value of the issueBackmatterInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IssueBackmatterInfo }
     *     
     */
    public IssueBackmatterInfo getIssueBackmatterInfo() {
        return issueBackmatterInfo;
    }

    /**
     * Sets the value of the issueBackmatterInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssueBackmatterInfo }
     *     
     */
    public void setIssueBackmatterInfo(IssueBackmatterInfo value) {
        this.issueBackmatterInfo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
