//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.12 at 07:28:45 PM MSK 
//


package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CompanyName"/>
 *         &lt;element ref="{}Contact"/>
 *         &lt;element ref="{}ContactPerson"/>
 *         &lt;element ref="{}Deliverables"/>
 *         &lt;element ref="{}FilesToPublisher"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "companyName",
    "contact",
    "contactPerson",
    "deliverables",
    "filesToPublisher"
})
@XmlRootElement(name = "ExternalPublisher")
public class ExternalPublisher {

    @XmlElement(name = "CompanyName", required = true)
    protected String companyName;
    @XmlElement(name = "Contact", required = true)
    protected Contact contact;
    @XmlElement(name = "ContactPerson", required = true)
    protected ContactPerson contactPerson;
    @XmlElement(name = "Deliverables", required = true)
    protected Deliverables deliverables;
    @XmlElement(name = "FilesToPublisher", required = true)
    protected FilesToPublisher filesToPublisher;

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link Contact }
     *     
     */
    public Contact getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contact }
     *     
     */
    public void setContact(Contact value) {
        this.contact = value;
    }

    /**
     * Gets the value of the contactPerson property.
     * 
     * @return
     *     possible object is
     *     {@link ContactPerson }
     *     
     */
    public ContactPerson getContactPerson() {
        return contactPerson;
    }

    /**
     * Sets the value of the contactPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactPerson }
     *     
     */
    public void setContactPerson(ContactPerson value) {
        this.contactPerson = value;
    }

    /**
     * Gets the value of the deliverables property.
     * 
     * @return
     *     possible object is
     *     {@link Deliverables }
     *     
     */
    public Deliverables getDeliverables() {
        return deliverables;
    }

    /**
     * Sets the value of the deliverables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deliverables }
     *     
     */
    public void setDeliverables(Deliverables value) {
        this.deliverables = value;
    }

    /**
     * Gets the value of the filesToPublisher property.
     * 
     * @return
     *     possible object is
     *     {@link FilesToPublisher }
     *     
     */
    public FilesToPublisher getFilesToPublisher() {
        return filesToPublisher;
    }

    /**
     * Sets the value of the filesToPublisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilesToPublisher }
     *     
     */
    public void setFilesToPublisher(FilesToPublisher value) {
        this.filesToPublisher = value;
    }

}
