//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.19 at 06:11:57 PM MSK 
//


package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{}AplusplusRootFile"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}Archive"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}RenditionItem"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}Cover"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}WorkItem"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}APageFile"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}MediaObject"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="DiscreteObjectID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aplusplusRootFile",
    "archive",
    "renditionItem",
    "cover",
    "workItem",
    "aPageFile",
    "mediaObject"
})
@XmlRootElement(name = "File")
public class File {

    @XmlElement(name = "AplusplusRootFile")
    protected AplusplusRootFile aplusplusRootFile;
    @XmlElement(name = "Archive")
    protected Archive archive;
    @XmlElement(name = "RenditionItem")
    protected RenditionItem renditionItem;
    @XmlElement(name = "Cover")
    protected Cover cover;
    @XmlElement(name = "WorkItem")
    protected WorkItem workItem;
    @XmlElement(name = "APageFile")
    protected APageFile aPageFile;
    @XmlElement(name = "MediaObject")
    protected MediaObject mediaObject;
    @XmlAttribute(name = "DiscreteObjectID")
    protected String discreteObjectID;

    /**
     * Gets the value of the aplusplusRootFile property.
     * 
     * @return
     *     possible object is
     *     {@link AplusplusRootFile }
     *     
     */
    public AplusplusRootFile getAplusplusRootFile() {
        return aplusplusRootFile;
    }

    /**
     * Sets the value of the aplusplusRootFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link AplusplusRootFile }
     *     
     */
    public void setAplusplusRootFile(AplusplusRootFile value) {
        this.aplusplusRootFile = value;
    }

    /**
     * Gets the value of the archive property.
     * 
     * @return
     *     possible object is
     *     {@link Archive }
     *     
     */
    public Archive getArchive() {
        return archive;
    }

    /**
     * Sets the value of the archive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Archive }
     *     
     */
    public void setArchive(Archive value) {
        this.archive = value;
    }

    /**
     * Gets the value of the renditionItem property.
     * 
     * @return
     *     possible object is
     *     {@link RenditionItem }
     *     
     */
    public RenditionItem getRenditionItem() {
        return renditionItem;
    }

    /**
     * Sets the value of the renditionItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link RenditionItem }
     *     
     */
    public void setRenditionItem(RenditionItem value) {
        this.renditionItem = value;
    }

    /**
     * Gets the value of the cover property.
     * 
     * @return
     *     possible object is
     *     {@link Cover }
     *     
     */
    public Cover getCover() {
        return cover;
    }

    /**
     * Sets the value of the cover property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cover }
     *     
     */
    public void setCover(Cover value) {
        this.cover = value;
    }

    /**
     * Gets the value of the workItem property.
     * 
     * @return
     *     possible object is
     *     {@link WorkItem }
     *     
     */
    public WorkItem getWorkItem() {
        return workItem;
    }

    /**
     * Sets the value of the workItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkItem }
     *     
     */
    public void setWorkItem(WorkItem value) {
        this.workItem = value;
    }

    /**
     * Gets the value of the aPageFile property.
     * 
     * @return
     *     possible object is
     *     {@link APageFile }
     *     
     */
    public APageFile getAPageFile() {
        return aPageFile;
    }

    /**
     * Sets the value of the aPageFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link APageFile }
     *     
     */
    public void setAPageFile(APageFile value) {
        this.aPageFile = value;
    }

    /**
     * Gets the value of the mediaObject property.
     * 
     * @return
     *     possible object is
     *     {@link MediaObject }
     *     
     */
    public MediaObject getMediaObject() {
        return mediaObject;
    }

    /**
     * Sets the value of the mediaObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaObject }
     *     
     */
    public void setMediaObject(MediaObject value) {
        this.mediaObject = value;
    }

    /**
     * Gets the value of the discreteObjectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscreteObjectID() {
        return discreteObjectID;
    }

    /**
     * Sets the value of the discreteObjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscreteObjectID(String value) {
        this.discreteObjectID = value;
    }

}
