//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.12 at 07:28:45 PM MSK 
//

package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.spr.jfluxpackagegenerator.jobsheet.builder.JobSheetDirectChild;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PublisherInfo"/>
 *         &lt;element ref="{}JournalInfo"/>
 *         &lt;element ref="{}VolumeInfo"/>
 *         &lt;element ref="{}IssueInfo"/>
 *         &lt;element ref="{}ProductionInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "publisherInfo", "journalInfo", "volumeInfo", "issueInfo", "suppInfo",
		"productionInfo" })
@XmlRootElement(name = "IssueJobSheet")
public class IssueJobSheet implements JobSheetDirectChild {

	/**
	 * @return the suppInfo
	 */
	public SuppInfo getSuppInfo() {
		return suppInfo;
	}

	/**
	 * @param suppInfo
	 *            the suppInfo to set
	 */
	@Override
	public void setSuppInfo(final SuppInfo suppInfo) {
		this.suppInfo = suppInfo;
	}

	@XmlElement(name = "PublisherInfo", required = true)
	protected PublisherInfo publisherInfo;

	@XmlElement(name = "JournalInfo", required = true)
	protected JournalInfo journalInfo;

	@XmlElement(name = "VolumeInfo", required = true)
	protected VolumeInfo volumeInfo;

	@XmlElement(name = "IssueInfo", required = true)
	protected IssueInfo issueInfo;

	@XmlElement(name = "SuppInfo", required = true)
	protected SuppInfo suppInfo;

	@XmlElement(name = "ProductionInfo", required = true)
	protected ProductionInfo productionInfo;

	/**
	 * Gets the value of the publisherInfo property.
	 * 
	 * @return possible object is {@link PublisherInfo }
	 */
	public PublisherInfo getPublisherInfo() {
		return publisherInfo;
	}

	/**
	 * Sets the value of the publisherInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link PublisherInfo }
	 */
	@Override
	public void setPublisherInfo(final PublisherInfo value) {
		this.publisherInfo = value;
	}

	/**
	 * Gets the value of the journalInfo property.
	 * 
	 * @return possible object is {@link JournalInfo }
	 */
	public JournalInfo getJournalInfo() {
		return journalInfo;
	}

	/**
	 * Sets the value of the journalInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link JournalInfo }
	 */
	@Override
	public void setJournalInfo(final JournalInfo value) {
		this.journalInfo = value;
	}

	/**
	 * Gets the value of the volumeInfo property.
	 * 
	 * @return possible object is {@link VolumeInfo }
	 */
	public VolumeInfo getVolumeInfo() {
		return volumeInfo;
	}

	/**
	 * Sets the value of the volumeInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link VolumeInfo }
	 */
	public void setVolumeInfo(final VolumeInfo value) {
		this.volumeInfo = value;
	}

	/**
	 * Gets the value of the issueInfo property.
	 * 
	 * @return possible object is {@link IssueInfo }
	 */
	public IssueInfo getIssueInfo() {
		return issueInfo;
	}

	/**
	 * Sets the value of the issueInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link IssueInfo }
	 */
	public void setIssueInfo(final IssueInfo value) {
		this.issueInfo = value;
	}

	/**
	 * Gets the value of the productionInfo property.
	 * 
	 * @return possible object is {@link ProductionInfo }
	 */
	public ProductionInfo getProductionInfo() {
		return productionInfo;
	}

	/**
	 * Sets the value of the productionInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link ProductionInfo }
	 */
	@Override
	public void setProductionInfo(final ProductionInfo value) {
		this.productionInfo = value;
	}

}
