//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 04:34:52 PM MSK 
//


package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OnlineDate"/>
 *         &lt;element ref="{}CoverDate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "onlineDate",
    "coverDate"
})
@XmlRootElement(name = "IssueHistory")
public class IssueHistory {

    @XmlElement(name = "OnlineDate", required = true)
    protected OnlineDate onlineDate;
    @XmlElement(name = "CoverDate", required = true)
    protected CoverDate coverDate;

    /**
     * Gets the value of the onlineDate property.
     * 
     * @return
     *     possible object is
     *     {@link OnlineDate }
     *     
     */
    public OnlineDate getOnlineDate() {
        return onlineDate;
    }

    /**
     * Sets the value of the onlineDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnlineDate }
     *     
     */
    public void setOnlineDate(OnlineDate value) {
        this.onlineDate = value;
    }

    /**
     * Gets the value of the coverDate property.
     * 
     * @return
     *     possible object is
     *     {@link CoverDate }
     *     
     */
    public CoverDate getCoverDate() {
        return coverDate;
    }

    /**
     * Sets the value of the coverDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverDate }
     *     
     */
    public void setCoverDate(CoverDate value) {
        this.coverDate = value;
    }

}
