//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.12 at 07:28:45 PM MSK 
//


package com.spr.jfluxpackagegenerator.jobsheet;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{}DataObject" maxOccurs="2" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}ImageObject"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}AudioObject" maxOccurs="2" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}VideoObject" maxOccurs="2" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}TextObject" maxOccurs="2" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataObject",
    "imageObject",
    "audioObject",
    "videoObject",
    "textObject"
})
@XmlRootElement(name = "MediaObject")
public class MediaObject {

    @XmlElement(name = "DataObject")
    protected List<DataObject> dataObject;
    @XmlElement(name = "ImageObject")
    protected ImageObject imageObject;
    @XmlElement(name = "AudioObject")
    protected List<AudioObject> audioObject;
    @XmlElement(name = "VideoObject")
    protected List<VideoObject> videoObject;
    @XmlElement(name = "TextObject")
    protected List<TextObject> textObject;

    /**
     * Gets the value of the dataObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataObject }
     * 
     * 
     */
    public List<DataObject> getDataObject() {
        if (dataObject == null) {
            dataObject = new ArrayList<DataObject>();
        }
        return this.dataObject;
    }

    /**
     * Gets the value of the imageObject property.
     * 
     * @return
     *     possible object is
     *     {@link ImageObject }
     *     
     */
    public ImageObject getImageObject() {
        return imageObject;
    }

    /**
     * Sets the value of the imageObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageObject }
     *     
     */
    public void setImageObject(ImageObject value) {
        this.imageObject = value;
    }

    /**
     * Gets the value of the audioObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audioObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudioObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AudioObject }
     * 
     * 
     */
    public List<AudioObject> getAudioObject() {
        if (audioObject == null) {
            audioObject = new ArrayList<AudioObject>();
        }
        return this.audioObject;
    }

    /**
     * Gets the value of the videoObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the videoObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVideoObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VideoObject }
     * 
     * 
     */
    public List<VideoObject> getVideoObject() {
        if (videoObject == null) {
            videoObject = new ArrayList<VideoObject>();
        }
        return this.videoObject;
    }

    /**
     * Gets the value of the textObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextObject }
     * 
     * 
     */
    public List<TextObject> getTextObject() {
        if (textObject == null) {
            textObject = new ArrayList<TextObject>();
        }
        return this.textObject;
    }

}
