//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 04:34:52 PM MSK 
//

package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.spr.jfluxpackagegenerator.jobsheet
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _CoverFirstPage_QNAME = new QName("", "CoverFirstPage");
	private final static QName _Email_QNAME = new QName("", "Email");
	private final static QName _VolumeIDStart_QNAME = new QName("", "VolumeIDStart");
	private final static QName _ArticleSubCategory_QNAME = new QName("", "ArticleSubCategory");
	private final static QName _GivenName_QNAME = new QName("", "GivenName");
	private final static QName _OrgName_QNAME = new QName("", "OrgName");
	private final static QName _ArticleCategory_QNAME = new QName("", "ArticleCategory");
	private final static QName _CopyrightHolderName_QNAME = new QName("", "CopyrightHolderName");
	private final static QName _Particle_QNAME = new QName("", "Particle");
	private final static QName _Month_QNAME = new QName("", "Month");
	private final static QName _CompanyName_QNAME = new QName("", "CompanyName");
	private final static QName _JournalID_QNAME = new QName("", "JournalID");
	private final static QName _CopyrightYear_QNAME = new QName("", "CopyrightYear");
	private final static QName _JournalPrintISSN_QNAME = new QName("", "JournalPrintISSN");
	private final static QName _Street_QNAME = new QName("", "Street");
	private final static QName _PublisherImprintName_QNAME = new QName("", "PublisherImprintName");
	private final static QName _JournalTitle_QNAME = new QName("", "JournalTitle");
	private final static QName _ArticleFirstPage_QNAME = new QName("", "ArticleFirstPage");
	private final static QName _InstitutionalAuthorName_QNAME = new QName("", "InstitutionalAuthorName");
	private final static QName _IssueIDEnd_QNAME = new QName("", "IssueIDEnd");
	private final static QName _City_QNAME = new QName("", "City");
	private final static QName _Postcode_QNAME = new QName("", "Postcode");
	private final static QName _ArticleDOI_QNAME = new QName("", "ArticleDOI");
	private final static QName _ArticleSequenceNumber_QNAME = new QName("", "ArticleSequenceNumber");
	private final static QName _Suffix_QNAME = new QName("", "Suffix");
	private final static QName _State_QNAME = new QName("", "State");
	private final static QName _PublisherName_QNAME = new QName("", "PublisherName");
	private final static QName _ArticleID_QNAME = new QName("", "ArticleID");
	private final static QName _VolumeIDEnd_QNAME = new QName("", "VolumeIDEnd");
	private final static QName _FamilyName_QNAME = new QName("", "FamilyName");
	private final static QName _IssueArticleCount_QNAME = new QName("", "IssueArticleCount");
	private final static QName _ArticleLastPage_QNAME = new QName("", "ArticleLastPage");
	private final static QName _IssueFrontmatterLastPage_QNAME = new QName("", "IssueFrontmatterLastPage");
	private final static QName _Prefix_QNAME = new QName("", "Prefix");
	private final static QName _JournalElectronicISSN_QNAME = new QName("", "JournalElectronicISSN");
	private final static QName _URL_QNAME = new QName("", "URL");
	private final static QName _PublisherLocation_QNAME = new QName("", "PublisherLocation");
	private final static QName _VolumeIssueCount_QNAME = new QName("", "VolumeIssueCount");
	private final static QName _IssueBackmatterLastPage_QNAME = new QName("", "IssueBackmatterLastPage");
	private final static QName _JournalSPIN_QNAME = new QName("", "JournalSPIN");
	private final static QName _IssueBackmatterFirstPage_QNAME = new QName("", "IssueBackmatterFirstPage");
	private final static QName _Phone_QNAME = new QName("", "Phone");
	private final static QName _IssueIDStart_QNAME = new QName("", "IssueIDStart");
	private final static QName _IssueFrontmatterFirstPage_QNAME = new QName("", "IssueFrontmatterFirstPage");
	private final static QName _Postbox_QNAME = new QName("", "Postbox");
	private final static QName _ArticleEditorialResponsibility_QNAME = new QName("", "ArticleEditorialResponsibility");
	private final static QName _JournalAbbreviatedTitle_QNAME = new QName("", "JournalAbbreviatedTitle");
	private final static QName _Year_QNAME = new QName("", "Year");
	private final static QName _OrgDivision_QNAME = new QName("", "OrgDivision");
	private final static QName _CoverLastPage_QNAME = new QName("", "CoverLastPage");
	private final static QName _ArticleCitationID_QNAME = new QName("", "ArticleCitationID");
	private final static QName _PublisherURL_QNAME = new QName("", "PublisherURL");
	private final static QName _Fax_QNAME = new QName("", "Fax");
	private final static QName _JournalSubTitle_QNAME = new QName("", "JournalSubTitle");
	private final static QName _Day_QNAME = new QName("", "Day");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * com.spr.jfluxpackagegenerator.jobsheet
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link ArticleClassification }
	 * 
	 */
	public ArticleClassification createArticleClassification() {
		return new ArticleClassification();
	}

	/**
	 * Create an instance of {@link ArticleHistory }
	 * 
	 */
	public ArticleHistory createArticleHistory() {
		return new ArticleHistory();
	}

	/**
	 * Create an instance of {@link ArticleFundingInformation }
	 * 
	 */
	public ArticleFundingInformation createArticleFundingInformation() {
		return new ArticleFundingInformation();
	}

	/**
	 * Create an instance of {@link ArticleGrants }
	 * 
	 */
	public ArticleGrants createArticleGrants() {
		return new ArticleGrants();
	}

	/**
	 * Create an instance of {@link ArticleFundingInformation.Fund }
	 * 
	 */
	public ArticleFundingInformation.Fund createArticleFundingInformationFund() {
		return new ArticleFundingInformation.Fund();
	}

	/**
	 * Create an instance of {@link ArticleClassification.ClassificationGroup }
	 * 
	 */
	public ArticleClassification.ClassificationGroup createArticleClassificationClassificationGroup() {
		return new ArticleClassification.ClassificationGroup();
	}

	/**
	 * Create an instance of {@link Archive }
	 * 
	 */
	public Archive createArchive() {
		return new Archive();
	}

	/**
	 * Create an instance of {@link ArticleSuperTitle }
	 * 
	 */
	public ArticleSuperTitle createArticleSuperTitle() {
		return new ArticleSuperTitle();
	}

	/**
	 * Create an instance of {@link AuthorGroup }
	 * 
	 */
	public AuthorGroup createAuthorGroup() {
		return new AuthorGroup();
	}

	/**
	 * Create an instance of {@link Author }
	 * 
	 */
	public Author createAuthor() {
		return new Author();
	}

	/**
	 * Create an instance of {@link AuthorName }
	 * 
	 */
	public AuthorName createAuthorName() {
		return new AuthorName();
	}

	/**
	 * Create an instance of {@link Contact }
	 * 
	 */
	public Contact createContact() {
		return new Contact();
	}

	/**
	 * Create an instance of {@link Country }
	 * 
	 */
	public Country createCountry() {
		return new Country();
	}

	/**
	 * Create an instance of {@link InstitutionalAuthor }
	 * 
	 */
	public InstitutionalAuthor createInstitutionalAuthor() {
		return new InstitutionalAuthor();
	}

	/**
	 * Create an instance of {@link Affiliation }
	 * 
	 */
	public Affiliation createAffiliation() {
		return new Affiliation();
	}

	/**
	 * Create an instance of {@link OrgAddress }
	 * 
	 */
	public OrgAddress createOrgAddress() {
		return new OrgAddress();
	}

	/**
	 * Create an instance of {@link WorkItem }
	 * 
	 */
	public WorkItem createWorkItem() {
		return new WorkItem();
	}

	/**
	 * Create an instance of {@link ContactPerson }
	 * 
	 */
	public ContactPerson createContactPerson() {
		return new ContactPerson();
	}

	/**
	 * Create an instance of {@link ContactPersonName }
	 * 
	 */
	public ContactPersonName createContactPersonName() {
		return new ContactPersonName();
	}

	/**
	 * Create an instance of {@link BodyRef }
	 * 
	 */
	public BodyRef createBodyRef() {
		return new BodyRef();
	}

	/**
	 * Create an instance of
	 * {@link com.spr.jfluxpackagegenerator.jobsheet.OnlineDate }
	 * 
	 */
	public com.spr.jfluxpackagegenerator.jobsheet.OnlineDate createOnlineDate() {
		return new com.spr.jfluxpackagegenerator.jobsheet.OnlineDate();
	}

	/**
	 * Create an instance of {@link IssueJobSheet }
	 * 
	 */
	public IssueJobSheet createIssueJobSheet() {
		return new IssueJobSheet();
	}

	/**
	 * Create an instance of {@link PublisherInfo }
	 * 
	 */
	public PublisherInfo createPublisherInfo() {
		return new PublisherInfo();
	}

	/**
	 * Create an instance of {@link JournalInfo }
	 * 
	 */
	public JournalInfo createJournalInfo() {
		return new JournalInfo();
	}

	/**
	 * Create an instance of {@link JournalSubjectGroup }
	 * 
	 */
	public JournalSubjectGroup createJournalSubjectGroup() {
		return new JournalSubjectGroup();
	}

	/**
	 * Create an instance of {@link JournalSubject }
	 * 
	 */
	public JournalSubject createJournalSubject() {
		return new JournalSubject();
	}

	/**
	 * Create an instance of {@link VolumeInfo }
	 * 
	 */
	public VolumeInfo createVolumeInfo() {
		return new VolumeInfo();
	}

	/**
	 * Create an instance of {@link IssueInfo }
	 * 
	 */
	public IssueInfo createIssueInfo() {
		return new IssueInfo();
	}

	/**
	 * Create an instance of {@link SuppInfo }
	 * 
	 */
	public SuppInfo createSuppInfo() {
		return new SuppInfo();
	}

	/**
	 * Create an instance of {@link IssueTitle }
	 * 
	 */
	public IssueTitle createIssueTitle() {
		return new IssueTitle();
	}

	/**
	 * Create an instance of {@link IssueHistory }
	 * 
	 */
	public IssueHistory createIssueHistory() {
		return new IssueHistory();
	}

	/**
	 * Create an instance of {@link CoverDate }
	 * 
	 */
	public CoverDate createCoverDate() {
		return new CoverDate();
	}

	/**
	 * Create an instance of {@link IssueCopyright }
	 * 
	 */
	public IssueCopyright createIssueCopyright() {
		return new IssueCopyright();
	}

	/**
	 * Create an instance of {@link ProductionInfo }
	 * 
	 */
	public ProductionInfo createProductionInfo() {
		return new ProductionInfo();
	}

	/**
	 * Create an instance of {@link DiscreteIssueObjectInfo }
	 * 
	 */
	public DiscreteIssueObjectInfo createDiscreteIssueObjectInfo() {
		return new DiscreteIssueObjectInfo();
	}

	/**
	 * Create an instance of {@link CoverInfo }
	 * 
	 */
	public CoverInfo createCoverInfo() {
		return new CoverInfo();
	}

	/**
	 * Create an instance of {@link IssueFrontmatterInfo }
	 * 
	 */
	public IssueFrontmatterInfo createIssueFrontmatterInfo() {
		return new IssueFrontmatterInfo();
	}

	/**
	 * Create an instance of {@link ArticleInfo }
	 * 
	 */
	public ArticleInfo createArticleInfo() {
		return new ArticleInfo();
	}

	/**
	 * Create an instance of {@link ArticleExternalID }
	 * 
	 */
	public ArticleExternalID createArticleExternalID() {
		return new ArticleExternalID();
	}

	/**
	 * Create an instance of {@link ArticleRelatedObject }
	 * 
	 */
	public ArticleRelatedObject createArticleRelatedObject() {
		return new ArticleRelatedObject();
	}

	/**
	 * Create an instance of {@link ArticleTitle }
	 * 
	 */
	public ArticleTitle createArticleTitle() {
		return new ArticleTitle();
	}

	/**
	 * Create an instance of {@link ArticleSubTitle }
	 * 
	 */
	public ArticleSubTitle createArticleSubTitle() {
		return new ArticleSubTitle();
	}

	/**
	 * Create an instance of {@link ArticleCollection }
	 * 
	 */
	public ArticleCollection createArticleCollection() {
		return new ArticleCollection();
	}

	/**
	 * Create an instance of {@link ArticleHistory.RegistrationDate }
	 * 
	 */
	public ArticleHistory.RegistrationDate createArticleHistoryRegistrationDate() {
		return new ArticleHistory.RegistrationDate();
	}

	/**
	 * Create an instance of {@link ArticleHistory.Received }
	 * 
	 */
	public ArticleHistory.Received createArticleHistoryReceived() {
		return new ArticleHistory.Received();
	}

	/**
	 * Create an instance of {@link ArticleHistory.Revised }
	 * 
	 */
	public ArticleHistory.Revised createArticleHistoryRevised() {
		return new ArticleHistory.Revised();
	}

	/**
	 * Create an instance of {@link ArticleHistory.Accepted }
	 * 
	 */
	public ArticleHistory.Accepted createArticleHistoryAccepted() {
		return new ArticleHistory.Accepted();
	}

	/**
	 * Create an instance of {@link ArticleHistory.OnlineDate }
	 * 
	 */
	public ArticleHistory.OnlineDate createArticleHistoryOnlineDate() {
		return new ArticleHistory.OnlineDate();
	}

	/**
	 * Create an instance of {@link ArticleCopyright }
	 * 
	 */
	public ArticleCopyright createArticleCopyright() {
		return new ArticleCopyright();
	}

	/**
	 * Create an instance of {@link ArticleGrants.MetadataGrant }
	 * 
	 */
	public ArticleGrants.MetadataGrant createArticleGrantsMetadataGrant() {
		return new ArticleGrants.MetadataGrant();
	}

	/**
	 * Create an instance of {@link ArticleGrants.AbstractGrant }
	 * 
	 */
	public ArticleGrants.AbstractGrant createArticleGrantsAbstractGrant() {
		return new ArticleGrants.AbstractGrant();
	}

	/**
	 * Create an instance of {@link ArticleGrants.BodyPDFGrant }
	 * 
	 */
	public ArticleGrants.BodyPDFGrant createArticleGrantsBodyPDFGrant() {
		return new ArticleGrants.BodyPDFGrant();
	}

	/**
	 * Create an instance of {@link ArticleGrants.BodyHTMLGrant }
	 * 
	 */
	public ArticleGrants.BodyHTMLGrant createArticleGrantsBodyHTMLGrant() {
		return new ArticleGrants.BodyHTMLGrant();
	}

	/**
	 * Create an instance of {@link ArticleGrants.BibliographyGrant }
	 * 
	 */
	public ArticleGrants.BibliographyGrant createArticleGrantsBibliographyGrant() {
		return new ArticleGrants.BibliographyGrant();
	}

	/**
	 * Create an instance of {@link ArticleGrants.ESMGrant }
	 * 
	 */
	public ArticleGrants.ESMGrant createArticleGrantsESMGrant() {
		return new ArticleGrants.ESMGrant();
	}

	/**
	 * Create an instance of {@link ArticleContext }
	 * 
	 */
	public ArticleContext createArticleContext() {
		return new ArticleContext();
	}

	/**
	 * Create an instance of {@link IssueBackmatterInfo }
	 * 
	 */
	public IssueBackmatterInfo createIssueBackmatterInfo() {
		return new IssueBackmatterInfo();
	}

	/**
	 * Create an instance of {@link WorkflowInfo }
	 * 
	 */
	public WorkflowInfo createWorkflowInfo() {
		return new WorkflowInfo();
	}

	/**
	 * Create an instance of {@link Priority }
	 * 
	 */
	public Priority createPriority() {
		return new Priority();
	}

	/**
	 * Create an instance of {@link Supplier }
	 * 
	 */
	public Supplier createSupplier() {
		return new Supplier();
	}

	/**
	 * Create an instance of {@link ExternalPublisher }
	 * 
	 */
	public ExternalPublisher createExternalPublisher() {
		return new ExternalPublisher();
	}

	/**
	 * Create an instance of {@link Deliverables }
	 * 
	 */
	public Deliverables createDeliverables() {
		return new Deliverables();
	}

	/**
	 * Create an instance of {@link DeliverablesForCompoundObjects }
	 * 
	 */
	public DeliverablesForCompoundObjects createDeliverablesForCompoundObjects() {
		return new DeliverablesForCompoundObjects();
	}

	/**
	 * Create an instance of {@link DeliverablesForDiscreteObjects }
	 * 
	 */
	public DeliverablesForDiscreteObjects createDeliverablesForDiscreteObjects() {
		return new DeliverablesForDiscreteObjects();
	}

	/**
	 * Create an instance of {@link FilesToPublisher }
	 * 
	 */
	public FilesToPublisher createFilesToPublisher() {
		return new FilesToPublisher();
	}

	/**
	 * Create an instance of {@link ContentFiles }
	 * 
	 */
	public ContentFiles createContentFiles() {
		return new ContentFiles();
	}

	/**
	 * Create an instance of {@link File }
	 * 
	 */
	public File createFile() {
		return new File();
	}

	/**
	 * Create an instance of {@link AplusplusRootFile }
	 * 
	 */
	public AplusplusRootFile createAplusplusRootFile() {
		return new AplusplusRootFile();
	}

	/**
	 * Create an instance of {@link RenditionItem }
	 * 
	 */
	public RenditionItem createRenditionItem() {
		return new RenditionItem();
	}

	/**
	 * Create an instance of {@link Cover }
	 * 
	 */
	public Cover createCover() {
		return new Cover();
	}

	/**
	 * Create an instance of {@link CoverFigure }
	 * 
	 */
	public CoverFigure createCoverFigure() {
		return new CoverFigure();
	}

	/**
	 * Create an instance of {@link MediaObject }
	 * 
	 */
	public MediaObject createMediaObject() {
		return new MediaObject();
	}

	/**
	 * Create an instance of {@link DataObject }
	 * 
	 */
	public DataObject createDataObject() {
		return new DataObject();
	}

	/**
	 * Create an instance of {@link ImageObject }
	 * 
	 */
	public ImageObject createImageObject() {
		return new ImageObject();
	}

	/**
	 * Create an instance of {@link AudioObject }
	 * 
	 */
	public AudioObject createAudioObject() {
		return new AudioObject();
	}

	/**
	 * Create an instance of {@link VideoObject }
	 * 
	 */
	public VideoObject createVideoObject() {
		return new VideoObject();
	}

	/**
	 * Create an instance of {@link TextObject }
	 * 
	 */
	public TextObject createTextObject() {
		return new TextObject();
	}

	/**
	 * Create an instance of {@link APageFile }
	 * 
	 */
	public APageFile createAPageFile() {
		return new APageFile();
	}

	/**
	 * Create an instance of {@link JobSheet }
	 * 
	 */
	public JobSheet createJobSheet() {
		return new JobSheet();
	}

	/**
	 * Create an instance of {@link ArticleJobSheet }
	 * 
	 */
	public ArticleJobSheet createArticleJobSheet() {
		return new ArticleJobSheet();
	}

	/**
	 * Create an instance of {@link ArticleFundingInformation.Fund.FunderName }
	 * 
	 */
	public ArticleFundingInformation.Fund.FunderName createArticleFundingInformationFundFunderName() {
		return new ArticleFundingInformation.Fund.FunderName();
	}

	/**
	 * Create an instance of {@link ArticleFundingInformation.Fund.GrantNumber }
	 * 
	 */
	public ArticleFundingInformation.Fund.GrantNumber createArticleFundingInformationFundGrantNumber() {
		return new ArticleFundingInformation.Fund.GrantNumber();
	}

	/**
	 * Create an instance of
	 * {@link ArticleClassification.ClassificationGroup.CharacteristicValue }
	 * 
	 */
	public ArticleClassification.ClassificationGroup.CharacteristicValue createArticleClassificationClassificationGroupCharacteristicValue() {
		return new ArticleClassification.ClassificationGroup.CharacteristicValue();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "CoverFirstPage")
	public JAXBElement<String> createCoverFirstPage(final String value) {
		return new JAXBElement<String>(_CoverFirstPage_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Email")
	public JAXBElement<String> createEmail(final String value) {
		return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "VolumeIDStart")
	public JAXBElement<String> createVolumeIDStart(final String value) {
		return new JAXBElement<String>(_VolumeIDStart_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ArticleSubCategory")
	public JAXBElement<String> createArticleSubCategory(final String value) {
		return new JAXBElement<String>(_ArticleSubCategory_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "GivenName")
	public JAXBElement<String> createGivenName(final String value) {
		return new JAXBElement<String>(_GivenName_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "OrgName")
	public JAXBElement<String> createOrgName(final String value) {
		return new JAXBElement<String>(_OrgName_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ArticleCategory")
	public JAXBElement<String> createArticleCategory(final String value) {
		return new JAXBElement<String>(_ArticleCategory_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "CopyrightHolderName")
	public JAXBElement<String> createCopyrightHolderName(final String value) {
		return new JAXBElement<String>(_CopyrightHolderName_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Particle")
	public JAXBElement<String> createParticle(final String value) {
		return new JAXBElement<String>(_Particle_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Month")
	public JAXBElement<String> createMonth(final String value) {
		return new JAXBElement<String>(_Month_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "CompanyName")
	public JAXBElement<String> createCompanyName(final String value) {
		return new JAXBElement<String>(_CompanyName_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "JournalID")
	public JAXBElement<String> createJournalID(final String value) {
		return new JAXBElement<String>(_JournalID_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "CopyrightYear")
	public JAXBElement<String> createCopyrightYear(final String value) {
		return new JAXBElement<String>(_CopyrightYear_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "JournalPrintISSN")
	public JAXBElement<String> createJournalPrintISSN(final String value) {
		return new JAXBElement<String>(_JournalPrintISSN_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Street")
	public JAXBElement<String> createStreet(final String value) {
		return new JAXBElement<String>(_Street_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "PublisherImprintName")
	public JAXBElement<String> createPublisherImprintName(final String value) {
		return new JAXBElement<String>(_PublisherImprintName_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "JournalTitle")
	public JAXBElement<String> createJournalTitle(final String value) {
		return new JAXBElement<String>(_JournalTitle_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ArticleFirstPage")
	public JAXBElement<String> createArticleFirstPage(final String value) {
		return new JAXBElement<String>(_ArticleFirstPage_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "InstitutionalAuthorName")
	public JAXBElement<String> createInstitutionalAuthorName(final String value) {
		return new JAXBElement<String>(_InstitutionalAuthorName_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IssueIDEnd")
	public JAXBElement<String> createIssueIDEnd(final String value) {
		return new JAXBElement<String>(_IssueIDEnd_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "City")
	public JAXBElement<String> createCity(final String value) {
		return new JAXBElement<String>(_City_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Postcode")
	public JAXBElement<String> createPostcode(final String value) {
		return new JAXBElement<String>(_Postcode_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ArticleDOI")
	public JAXBElement<String> createArticleDOI(final String value) {
		return new JAXBElement<String>(_ArticleDOI_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ArticleSequenceNumber")
	public JAXBElement<String> createArticleSequenceNumber(final String value) {
		return new JAXBElement<String>(_ArticleSequenceNumber_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Suffix")
	public JAXBElement<String> createSuffix(final String value) {
		return new JAXBElement<String>(_Suffix_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "State")
	public JAXBElement<String> createState(final String value) {
		return new JAXBElement<String>(_State_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "PublisherName")
	public JAXBElement<String> createPublisherName(final String value) {
		return new JAXBElement<String>(_PublisherName_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ArticleID")
	public JAXBElement<String> createArticleID(final String value) {
		return new JAXBElement<String>(_ArticleID_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "VolumeIDEnd")
	public JAXBElement<String> createVolumeIDEnd(final String value) {
		return new JAXBElement<String>(_VolumeIDEnd_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "FamilyName")
	public JAXBElement<String> createFamilyName(final String value) {
		return new JAXBElement<String>(_FamilyName_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IssueArticleCount")
	public JAXBElement<String> createIssueArticleCount(final String value) {
		return new JAXBElement<String>(_IssueArticleCount_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ArticleLastPage")
	public JAXBElement<String> createArticleLastPage(final String value) {
		return new JAXBElement<String>(_ArticleLastPage_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IssueFrontmatterLastPage")
	public JAXBElement<String> createIssueFrontmatterLastPage(final String value) {
		return new JAXBElement<String>(_IssueFrontmatterLastPage_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Prefix")
	public JAXBElement<String> createPrefix(final String value) {
		return new JAXBElement<String>(_Prefix_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "JournalElectronicISSN")
	public JAXBElement<String> createJournalElectronicISSN(final String value) {
		return new JAXBElement<String>(_JournalElectronicISSN_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "URL")
	public JAXBElement<String> createURL(final String value) {
		return new JAXBElement<String>(_URL_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "PublisherLocation")
	public JAXBElement<String> createPublisherLocation(final String value) {
		return new JAXBElement<String>(_PublisherLocation_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "VolumeIssueCount")
	public JAXBElement<String> createVolumeIssueCount(final String value) {
		return new JAXBElement<String>(_VolumeIssueCount_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IssueBackmatterLastPage")
	public JAXBElement<String> createIssueBackmatterLastPage(final String value) {
		return new JAXBElement<String>(_IssueBackmatterLastPage_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "JournalSPIN")
	public JAXBElement<String> createJournalSPIN(final String value) {
		return new JAXBElement<String>(_JournalSPIN_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IssueBackmatterFirstPage")
	public JAXBElement<String> createIssueBackmatterFirstPage(final String value) {
		return new JAXBElement<String>(_IssueBackmatterFirstPage_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Phone")
	public JAXBElement<String> createPhone(final String value) {
		return new JAXBElement<String>(_Phone_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IssueIDStart")
	public JAXBElement<String> createIssueIDStart(final String value) {
		return new JAXBElement<String>(_IssueIDStart_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IssueFrontmatterFirstPage")
	public JAXBElement<String> createIssueFrontmatterFirstPage(final String value) {
		return new JAXBElement<String>(_IssueFrontmatterFirstPage_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Postbox")
	public JAXBElement<String> createPostbox(final String value) {
		return new JAXBElement<String>(_Postbox_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ArticleEditorialResponsibility")
	public JAXBElement<String> createArticleEditorialResponsibility(final String value) {
		return new JAXBElement<String>(_ArticleEditorialResponsibility_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "JournalAbbreviatedTitle")
	public JAXBElement<String> createJournalAbbreviatedTitle(final String value) {
		return new JAXBElement<String>(_JournalAbbreviatedTitle_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Year")
	public JAXBElement<String> createYear(final String value) {
		return new JAXBElement<String>(_Year_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "OrgDivision")
	public JAXBElement<String> createOrgDivision(final String value) {
		return new JAXBElement<String>(_OrgDivision_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "CoverLastPage")
	public JAXBElement<String> createCoverLastPage(final String value) {
		return new JAXBElement<String>(_CoverLastPage_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ArticleCitationID")
	public JAXBElement<String> createArticleCitationID(final String value) {
		return new JAXBElement<String>(_ArticleCitationID_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "PublisherURL")
	public JAXBElement<String> createPublisherURL(final String value) {
		return new JAXBElement<String>(_PublisherURL_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Fax")
	public JAXBElement<String> createFax(final String value) {
		return new JAXBElement<String>(_Fax_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "JournalSubTitle")
	public JAXBElement<String> createJournalSubTitle(final String value) {
		return new JAXBElement<String>(_JournalSubTitle_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Day")
	public JAXBElement<String> createDay(final String value) {
		return new JAXBElement<String>(_Day_QNAME, String.class, null, value);
	}

}
