//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.12 at 07:28:45 PM MSK 
//


package com.spr.jfluxpackagegenerator.jobsheet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ExternalPublisher"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "externalPublisher"
})
@XmlRootElement(name = "Supplier")
public class Supplier {

    @XmlElement(name = "ExternalPublisher", required = true)
    protected ExternalPublisher externalPublisher;

    /**
     * Gets the value of the externalPublisher property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalPublisher }
     *     
     */
    public ExternalPublisher getExternalPublisher() {
        return externalPublisher;
    }

    /**
     * Sets the value of the externalPublisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalPublisher }
     *     
     */
    public void setExternalPublisher(ExternalPublisher value) {
        this.externalPublisher = value;
    }

}
